"""tools/ui_scaffold.py — Scaffolder Atomic Design para Vision-UI. ROOT JAIL AMD-01."""

from __future__ import annotations

from pathlib import Path
from typing import Final, Protocol

from pydantic import BaseModel

from core.blueprint_schema import BlueprintV1


class FileTools(Protocol):
    def write_file(self, relative: str | Path, content: str) -> Path: ...


ATOMIC_STRUCTURE: Final[dict[str, list[str]]] = {
    "atoms": ["Button", "Input", "Label", "Badge", "Spinner"],
    "molecules": ["FormField", "SearchBar", "Card", "Alert"],
    "organisms": ["Header", "DataTable", "Modal", "Sidebar"],
    "templates": ["DashboardLayout", "AuthLayout", "LandingLayout"],
    "pages": [],
}
_COMPONENT_PLACEHOLDER = (
    "// Placeholder — Vision-UI Gen (Prompt #15) rellena este componente.\n"
    "export default function {name}() {{ return null; }}\n"
)
_INDEX_PLACEHOLDER = "// Auto-generated by UIScaffolder\n"
_GLOBALS_CSS = (
    "/* globals.css — reset y estilos base */\n"
    "*, *::before, *::after { box-sizing: border-box; }\n"
    "body { margin: 0; font-family: var(--font-body, sans-serif); }\n"
)


class StyleGuide(BaseModel):
    color_primary: str = "#3B82F6"
    color_secondary: str = "#6B7280"
    color_danger: str = "#EF4444"
    color_success: str = "#10B981"
    font_body: str = "Inter"
    font_mono: str = "JetBrains Mono"
    spacing_base_px: int = 8
    border_radius: str = "0.5rem"
    dark_mode: bool = True


class UIScaffolder:
    """Crea la estructura de carpetas y archivos base del Design System."""

    def __init__(self, file_tools: FileTools) -> None:
        self._ft = file_tools

    async def scaffold_project(
        self,
        mission_id: str,
        output_base: str = "output/{mission_id}/frontend",
    ) -> list[str]:
        """Genera el esqueleto Atomic Design. Retorna lista de rutas relativas creadas."""
        base = output_base.format(mission_id=mission_id)
        created: list[str] = []

        for layer, components in ATOMIC_STRUCTURE.items():
            is_top = layer in ("templates", "pages")
            folder = f"src/{layer}" if is_top else f"src/components/{layer}"
            if not components:
                placeholder = f"{base}/{folder}/.gitkeep"
                self._ft.write_file(placeholder, "")
                created.append(placeholder)
                continue
            for name in components:
                path = f"{base}/{folder}/{name}/index.tsx"
                self._ft.write_file(path, _COMPONENT_PLACEHOLDER.format(name=name))
                created.append(path)

        for css_path, content in [
            (f"{base}/src/styles/tokens.css", ""),
            (f"{base}/src/styles/globals.css", _GLOBALS_CSS),
            (f"{base}/src/lib/api.ts", "// API client — generado por generate_api_client()\n"),
        ]:
            self._ft.write_file(css_path, content)
            created.append(css_path)

        index_path = f"{base}/src/index.tsx"
        self._ft.write_file(index_path, _INDEX_PLACEHOLDER)
        created.append(index_path)
        return created

    async def generate_design_tokens(self, style_guide: StyleGuide) -> str:
        """Genera tokens.css con variables CSS desde el StyleGuide."""
        sg = style_guide
        return "\n".join([
            ":root {",
            f"  --color-primary: {sg.color_primary}; /* brand */",
            f"  --color-secondary: {sg.color_secondary};",
            f"  --color-danger: {sg.color_danger};",
            f"  --color-success: {sg.color_success};",
            f"  --spacing-base: {sg.spacing_base_px}px;",
            f"  --font-body: '{sg.font_body}', sans-serif;",
            f"  --font-mono: '{sg.font_mono}', monospace;",
            f"  --border-radius: {sg.border_radius};",
            "}",
        ]) + "\n"

    async def generate_api_client(self, blueprint: BlueprintV1) -> str:
        """Genera lib/api.ts con una función fetch por ApiEndpoint del Blueprint."""
        lines = ["// Auto-generated API client for " + blueprint.product_name, ""]
        for ep in blueprint.api_endpoints:
            raw = ep.path.strip("/").replace("/", "_").replace("{", "").replace("}", "")
            fn_name = f"{ep.method.lower()}_{raw or 'root'}"
            lines += [
                f"export async function {fn_name}(init?: RequestInit): Promise<Response> {{",
                f"  return fetch('{ep.path}', {{ method: '{ep.method}', ...init }});",
                "}",
                "",
            ]
        return "\n".join(lines)
